name: CI/CD

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          target_branch: deploy
          build_dir: dist